### PR TITLE
Rebecca Faces

### PR DESCRIPTION
**Pull request by Zerodya**
Custom faces of Rebecca from Cyberpunk Edgerunners, tested on Waveshare V4 and Jayofelony fork v2.8.9 :)

### CODE REVIEW

**Comment by roodriiigooo** [comment]
Your work turned out really well! 
Congratulations!

**Comment by deox420** [comment]
Hey im using a waveshare_v3 its all ok it works but is misaligned. 
i went to /usr/local/lib/python3.9/dist-packages/pwnagotchi/ui/hw/ but there is no waveshare_v3 to change it. 
im using jayofelony last version.

**Comment by Zerodya** [comment]
Works as expected for me on waveshare_v4. Do you think it's an issue with my files or is it something else? Also misaligned how?

**Comment by deox420** [comment]
/usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/hw/ when i go to this directory it got a lot of interfaces like waveshare213d and lot more but not waveshare_3 there is a waveshare_V2 tho. 

The rebeca images apeared on the left edge i want to move them a little so is more centered.

I suppose is an issue with Jayofelony directories i guess. Somehow i got it to show with the waveshare_3 in the confg.toml but in that directory ( /usr/local/lib/python3.7/dist-packages/pwnagotchi/ui/hw/ ) it shows a lot of waveshare and inks but not that one. I tried changing somes to tried getting to move to the right, but nones work.

Sorry for my bad english, i don't know if i have explained myself well.

**Comment by Zerodya** [comment]
I think I see what you mean now, you can simply move it to the right by setting [ui.faces.position_x](https://github.com/jayofelony/pwnagotchi/blob/4861a0c08bd62638e3678e8bdf690ef0a093a4de/pwnagotchi/defaults.toml#L185) with a positive value in your config

**Comment by V0r-T3x** [comment]
I added the face list to Fancygotchi 2.0 themes. @Zerodya 
I gave all the credits with the links
you can see the list here: https://github.com/V0r-T3x/Fancygotchi_themes/tree/main/fancygotchi_2.0
if there is any problems, I can remove them.

**Pull request merged**
