### PR TITLE
MikuGotchi Faces

### PR DESCRIPTION
**Pull request by exosever**
Set of 25 sprites of Miku made for pwnagotchi v1.5.5 and above. Verified works on waveshare 3 and 4 formats.

### CODE REVIEW

**Comment by exosever** [comment]
Please let me know if I'm missing something, I'm very new to github and have had to learn what forks and pulls are. I fixed up the sprites to be decent quality, and I tried to set the readme correctly. If I know what's missing I'll be sure to fix it and try again!

**Comment by roodriiigooo** [comment]
Thank you very much !! 😃

**Comment by exosever** [comment]
Thank you too! I'm super stoked to be a part of this! I have another one as well, I'll get that request to you when the fork is good to go!

**Comment by V0r-T3x** [comment]
I added the face list to Fancygotchi 2.0 themes. @exosever 
I gave all the credits with the links
you can see the list here: https://github.com/V0r-T3x/Fancygotchi_themes/tree/main/fancygotchi_2.0
if there is any problems, I can remove them.

**Pull request merged**
